server:
  port: 8001

spring:
  application:
    name: content-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xcplus_content?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: dev
        group: xuecheng-plus-project
logging:
  level:
    com.xuecheng: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    path: "logs/${spring.application.name}"
